site_name: Javier Beteta - Landing Page
site_url: https://jbeteta-ies.github.io/jbeteta-ies.githib.io/
theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav: []

