site_name: Javier Beteta - Personal Site
copyright: '2025, Javier Beteta'
site_url: https://jbeteta-ies.github.io/jbeteta-ies.github.io/
theme:
  name: material
  favicon: img/favicon.svg
  logo: img/favicon.svg
  palette:
    primary: teal        # 👈 color de la barra superior
    accent: red  
  features:
    - content.code.copy

extra_css:
  - css/extra.css

plugins: []

markdown_extensions:
  - admonition
  - pymdownx.details
  - codehilite
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav: []

